### ISSUE TITLE
Typographical error in the equation documentation.

### ISSUE THREAD

**Issue by itsmohitanand** [kratzert/AGU2018#1]
https://github.com/kratzert/AGU2018/blob/589f6f95249903db6c4d4ccd58669b4c76870a64/code/model.py#L47

c_t = f_t \odot c_{t-1} + tanh(W_{hc} h_t + W_{xc} x_t + b_c)
should be replaced by,
c_t = f_t \odot c_{t-1} + i_t \odot tanh(W_{hc} h_{t-1} + W_{xc} x_t + b_c)

Suggestion for enhancing the readability of the code
g_t = tanh(W_{hc} h_{t-1} + W_{xc} x_t + b_c)
c_t =  f_t \odot c_{t-1} +i_t \odot g_t

**Comment by kratzert** [comment]
Thanks! Since you didn't send a MR I updated the equations in master
